<%
function getAdminLanguageArray(l) {;
	// Admin //////////
	l["general_infomation"] = "general_infomation";
	l["general_setting"] = "general_setting";
	l["category_manage"] = "category_manage";
	l["user_group"] = "user_group";
	l["smile_icon"] = "smile_icon";
	l["plugin_center"] = "plugin_center";
	l["user_right"] = "user_right";

	l["in_global_category"] = "in_global_category";
	l["global_category_desc"] = "global_category_desc";
	l["nothing"] = "nothing";
	l["name"] = "name";

	// category.asp
	l["category"] = "category";
	l["edit_category"] = "edit_category";
	l["add_category"] = "add_category";
	l["category_list"] = "category_list";
	l["category_name"] = "category_name";
	l["description"] = "description";
	l["intro"] = "intro";
	l["hidden"] = "hidden";
	l["hidden_desc"] = "hidden_desc";
	l["locked"] = "locked";
	l["locked_desc"] = "locked_desc";
	l["url"] = "url";
	l["order"] = "order";
	l["up"] = "up";
	l["down"] = "down";
	l["order_desc"] = "order_desc";
	l["delete_category_with_sub_desc"] = "delete_category_with_sub_desc";
	l["no_categories_desc"] = "no_categories_desc";


	// admin.asp
	l["site_version"] = "site_version";
	l["site_operate"] = "site_operate";
	l["open_site"] = "open_site";
	l["close_site"] = "close_site";
	l["clean_cache"] = "clean_cache";
	l["server_software"] = "server_software";
	l["server_time"] = "server_time";
	l["server_ip"] = "server_ip";
	l["application_path"] = "application_path";
	l["script_engine"] = "script_engine";
	l["obj_fso"] = "obj_fso";
	l["obj_xmlhttp"] = "obj_xmlhttp";
	l["obj_xmldom"] = "obj_xmldom";
	l["obj_stream"] = "obj_stream";
	l["object_desc"] = "object_desc";

	// setting.asp
	l["basic_setting"] = "basic_setting";
	l["skin_setting"] = "skin_setting";
	l["site_name"] = "site_name";
	l["site_description"] = "site_description";
	l["site_url"] = "site_url";
	l["site_path"] = "site_path";
	l["site_close_description"] = "site_close_description";
	l["html_allowed"] = "html_allowed";
	l["site_webmaster"] = "site_webmaster";
	l["webmaster_email"] = "webmaster_email";
	l["language_code"] = "language_code";
	l["what_language_code"] = "what_language_code";
	l["smile_icon_folder"] = "smile_icon_folder";
	l["default_skin"] = "default_skin";
	l["default_lang"] = "default_lang";
	l["default_style"] = "default_style";

	// smile.asp
	l["no_smiles_desc"] = "no_smiles_desc";
	l["add_smile_icon"] = "add_smile_icon";
	l["smile_desc"] = "smile_desc";
	l["picture"] = "picture";
	l["file_name"] = "file_name";
	l["new"] = "new";

	// plugin.asp
	l["no_plugins_desc"] = "no_plugins_desc";
	l["database_path"] = "database_path";
	l["in_folder"] = "in_folder";
	l["manage"] = "manage";
	l["database_connection_false"] = "database_connection_false";
	l["plugin_version"] = "plugin_version";
	l["plugin_path"] = "plugin_path";

	// usergroup.asp
	l["base_group_note_desc"] = "base_group_note_desc";
	l["delete_group_note_desc"] = "delete_group_note_desc";

	// userright.asp
	l["only_self"] = "only_self";
	l["only_comment"] = "only_comment";
}
%>