<%
function getNewsLanguageArray(l) {
	l["add_news"] = "add_news"
	l["news_manage"] = "news_manage"

	l["news_title"] = "news_title"
	l["source"] = "source"
	l["source_link"] = "source_link"
	l["summary"] = "summary"
	l["content"] = "content"
	l["publisher"] = "publisher"
	l["select_category"] = "select_category"
	l["smile_icon"] = "smile_icon"
	l["option"] = "option"

	l["built_file"] = "built_file"
	l["built_option"] = "built_option"
	l["custom"] = "custom"
	l["built_file_folder"] = "built_file_folder"
	l["file_name"] = "file_name"
	l["type"] = "type"
	l["built_file_name_desc"] = "built_file_name_desc"

	l["news_post_success"] = "news_post_success"
	l["news_edit_success"] = "news_edit_success"

	l["no_news_desc"] = "no_news_desc"

	l["enable_html"] = "enable_html"
	l["enable_ubb_code"] = "enable_ubb_code"
	l["auto_convert_url"] = "auto_convert_url"
	l["show_images"] = "show_images"
	l["show_medias"] = "show_medias"
	l["show_smiles"] = "show_smiles"

	// Admin //////////
	l["news_system_manage"] = "news_system_manage"
	l["delete_category_with_news_desc"] = "delete_category_with_news_desc"
}
%>