<%
function getMusicLanguageArray(l) {
	l["no_songs_desc"] = "no_songs_desc"
	l["song_name"] = "song_name"
	l["version"] = "version"
	l["author"] = "author"
	l["lyric"] = "lyric"
	l["copyrights"] = "copyrights"
	l["online_listen"] = "online_listen"
	l["in_album"] = "in_album"
	l["add_song"] = "add_song"
	l["add_album"] = "add_album"
	l["album_name"] = "album_name"
	l["no_album_desc"] = "no_album_desc"
	l["song_list"] = "song_list"
	l["album_list"] = "album_list"
	l["edit_album"] = "edit_album"
	l["edit_song"] = "edit_song"
	l["song_order"] = "song_order"
	l["select_add_song_desc"] = "select_add_song_desc"
	l["have_same_song_desc"] = "have_same_song_desc"
	l["not_find_song"] = "not_find_song"
}
%>